server:
  port: 9399

rpc:
  zk:
    root: "/rpc/root"
    connect-string: "192.168.0.11:2181"
    session-timeout: 5000
    connection-timeout: 5000
  network:
    port: 8848
  server:
    port: ${server.port}
    core-size: 4
    max-size: 8
